# Generated by Django 3.1.6 on 2021-02-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_yazi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
