# Generated by Django 3.1.6 on 2021-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yazi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/image'),
        ),
    ]
